name: Main-CI

on:
  push:
    branches: [ master ]

jobs:
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        env:
          CI: true
      - run: npm install
      - run: npm test --coverage


  deploy:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to GH Pages
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
      - run: git config --global user.name ${{secrets.GH_NAME}}
      - run: git config --global user.email ${{secrets.GH_EMAIL}}
      - run: git remote set-url origin https://${{secrets.GH_ACCESS_TOKEN}}@github.com/${{secrets.GH_USERNAME}}/ridiculously-over-engineered-calculator.git
      - run: npm run deploy
        env:
          CI: true

